### ISSUE TITLE
non-auth endpoints still send an Authorization header

### ISSUE THREAD

**Issue by teepark** [dropbox/dropbox-sdk-go-unofficial#7]
I encountered this with `list_folder/longpoll`. Even though it tries to [remove the Authorization header](https://github.com/dropbox/dropbox-sdk-go-unofficial/blob/master/dropbox/files/client.go#L1754), it actually gets [added later by the transport](https://github.com/golang/oauth2/blob/master/transport.go#L46), which used by everything in this package.

So without restructuring the client/transport to support going around the oauth2 transport entirely, everything gets the Authorization header.

This results in the Dropbox API rejecting the request with `Your request includes an Authorization header, but this function does not use it.`

**Comment by teepark** [comment]
Judging by [the user endpoint docs](https://www.dropbox.com/developers/documentation/http/documentation) it looks like this only affects `list_folder/longpoll`. Also none of the business endpoints support auth-less requests.

**Comment by diwakergupta** [comment]
@teepark bummer, thanks for the report. This definitely used to work, but the transport code has existed since 2014 so not sure what has changed. Do you mind including a verbose output for the failed invocation, along with the cmdline arguments?

**Comment by teepark** [comment]
@diwakergupta there weren't really any cmdline arguments involved, I was calling the go function [ListFolderLongpoll](https://github.com/dropbox/dropbox-sdk-go-unofficial/blob/master/dropbox/files/client.go#L1737).

It returned the error, `Error in call to API function "files/list_folder/longpoll": Your request includes an Authorization header, but this function does not use it.`

**Comment by hexasoftware** [comment]
I tried to use this method and had the same issue,

I noticed on the source: [dropbox/sdk.go:96](https://github.com/dropbox/dropbox-sdk-go-unofficial/blob/master/dropbox/sdk.go#L96-L98) an attempt to remove the "Authorization" header, but since for me the client is created with go oauth2 [dropbox/sdk:106](https://github.com/dropbox/dropbox-sdk-go-unofficial/blob/master/dropbox/sdk.go#L109-L114) the "authorization" header is still added at transport level

a workaround for me at: [dropbox/files/client.go:1806](https://github.com/dropbox/dropbox-sdk-go-unofficial/blob/master/dropbox/files/client.go#L1806) was a simple:
```Go
// cli := dbx.Client
cli := http.Client{}
```

**Comment by kerma** [comment]
Still broken :(

```
2018/11/01 22:32:29 req: &{POST https://notify.dropboxapi.com/2/files/list_folder/longpoll HTTP/1.1 1 1 map[Content-Type:[application/json]] {0xc00043b5c0} 0x11fee00 177 [] false notify.dropboxapi.com map[] map[] <nil> map[]   <nil> <nil> <nil> <nil>}
2018/11/01 22:32:29 resp: &{400 Bad Request 400 HTTP/1.1 1 1 map[Date:[Thu, 01 Nov 2018 20:32:29 GMT] Content-Type:[text/plain; charset=utf-8] Content-Length:[141] Cache-Control:[no-cache] Pragma:[no-cache] Server:[nginx] Connection:[keep-alive] X-Db-Timeout:[120] X-Dropbox-Request-Id:[c59903d299b17582bbbcce4923795464]] 0xc0001e0aa0 141 [] false false map[] 0xc000328300 0xc0003dc000}
Error in call to API function "files/list_folder/longpoll": Your request includes an Authorization header, but this function does not use it.
```

It's weird, because it looks like it should be working:
https://github.com/dropbox/dropbox-sdk-go-unofficial/blob/master/dropbox/files/client.go#L2385
https://github.com/dropbox/dropbox-sdk-go-unofficial/blob/master/dropbox/sdk.go#L139

I already started to believe the HTTP API was broken, but no. Testing with curl and it works as described. 

@hexasoftware workaround helped me as well, but I'd prefer not to patch vendor deps. @diwakergupta any ideas how to "fix" it without implementing my own `ListFolderLongpoll`?

**Comment by PtxuncGinovi4** [comment]
Please give me workaround

**Comment by andresmatasuarez** [comment]
any updates here? I'm struggling with the same thing

**Comment by rajatgoel** [comment]
Hi. I was able to write a dummy test code that makes an invalid request with and without the patch above and confirm that the its not complaining about the token anymore. 

Give it a try and if it doesn't work, feel free to re-open the ticket.
